name: Deploy Flask App to Kubernetes

on:
  push:
    branches:
      - main  # Adjust if using another branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          docker build -t dilliramshah4/flask-app:latest .
          docker push dilliramshah4/flask-app:latest

      - name: Set up Kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: v1.32.2  # Adjust if needed

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Update Kubeconfig
        run: |
          aws eks update-kubeconfig --region us-east-1 --name my-eks-cluster
          kubectl config current-context
          kubectl cluster-info

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f deployment.yml --validate=false
          kubectl apply -f service.yml --validate=false
          
      - name: Force Update Deployment to Pull Latest Image
        run: |
          kubectl set image deployment/flask-app flask-app=dilliramshah4/flask-app:latest --record

      - name: Wait for Pods to be Ready
        run: |
          kubectl rollout status deployment/flask-app

      - name: Verify Deployment
        run: |
          kubectl get pods
          kubectl get svc

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f deployment.yml --validate=false
          kubectl apply -f service.yml --validate=false

      - name: Force Restart Deployment (Pull Latest Image)
        run: |
          kubectl rollout restart deployment flask-app
          kubectl get pods
