name: Deploy Flask App to Kubernetes

on:
  push:
    branches:
      - main  # Change this if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          docker build -t dilliramshahu4/flask-app:latest .
          docker push dilliramshahu4/flask-app:latest

      - name: Set up Kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: v1.30.9  # Ensure it matches your EKS version

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Change this if needed

      - name: Update Kubeconfig
        run: |
          aws eks update-kubeconfig --region us-east-1 --name my-eks-cluster

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f deployment.yml
          if [ -f service.yml ]; then kubectl apply -f service.yml; fi  # Only apply if service.yml exists

      - name: Verify Deployment
        run: |
          kubectl get pods -A
          kubectl get svc -A
          