name: Deploy Flask App to Kubernetes

on:
  push:
    branches:
      - main  # Change this to your main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          docker build -t dilliramshah4/flask-app:latest .
          docker push dilliramshah4/flask-app:latest

      - name: Set up Kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: v1.32.2  # Change this to your K8s version

      # ✅ Step 1: Update Kubeconfig
      - name: Update Kubeconfig
        run: |
          aws eks update-kubeconfig --region us-east-1 --name my-eks-cluster
          kubectl config current-context  # Debugging step
          kubectl cluster-info            # Debugging step

      # ✅ Step 2: Debug Kubeconfig
      - name: Debug Kubernetes Configuration
        run: |
          echo "Kubeconfig:"
          cat ~/.kube/config

      # ✅ Step 3: Deploy with --validate=false
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f deployment.yml --validate=false
          kubectl apply -f service.yml --validate=false

      - name: Verify Deployment
        run: |
          kubectl get pods
          kubectl get svc
