name: Deploy Flask App to Minikube (Local)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Use Minikube's Docker
        run: |
          eval $(minikube docker-env)

      - name: Build Docker Image inside Minikube
        run: |
          docker build -t flask-notes-app .

      - name: Apply Kubernetes Manifests
        run: |
          kubectl apply -f deployment.yml
          kubectl apply -f service.yml

      - name: Restart Deployment (for updated image)
        run: |
          kubectl rollout restart deployment flask-app
          kubectl rollout status deployment flask-app
